apiVersion: v1
kind: Namespace
metadata:
    name: authentik-staging-2
    labels:
        pod-security.kubernetes.io/enforce: privileged
    annotations:
        volsync.backube/privileged-movers: "true"