apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-staging-2
  namespace: flux-system
spec:
  interval: 10h
  path: clusters/main/kubernetes/core/authentik-staging-2
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster